"""Field Theory bookmark catalog for Factor. Composio is not in this list."""

from __future__ import annotations

# category: skills | plugins | other
# disposition: add | builtin | shelf

ITEMS: list[dict[str, str]] = [
    # --- skills the company can turn on ---
    dict(id="openspec", name="OpenSpec", category="skills", kind="skill", disposition="add",
         repo="https://github.com/Fission-AI/OpenSpec", bookmark="2100625120691720385",
         risk="low", approval="no",
         summary="Spec-first change proposals before implementation."),
    dict(id="spec-kit", name="spec-kit", category="skills", kind="skill", disposition="add",
         repo="https://github.com/github/spec-kit", bookmark="2035687161471840641",
         risk="low", approval="no",
         summary="Specify, plan, and task a change before code."),
    dict(id="caveman", name="caveman", category="skills", kind="skill", disposition="add",
         repo="https://github.com/JuliusBrussee/caveman", bookmark="2100625120691720385",
         risk="low", approval="no",
         summary="Terse plans that cost fewer tokens."),
    dict(id="superpowers", name="Superpowers", category="skills", kind="skill", disposition="add",
         repo="https://github.com/obra/superpowers", bookmark="2035915909966229733",
         risk="low", approval="no",
         summary="A development method: clarify, test, review. Read it before installing the whole pack."),
    dict(id="gsd", name="Get Shit Done", category="skills", kind="skill", disposition="add",
         repo="https://github.com/gsd-build/get-shit-done", bookmark="2035915909966229733",
         risk="low", approval="no",
         summary="Planning and execution skills for a coding agent."),
    dict(id="agent-skills", name="Agent Skills", category="skills", kind="skill", disposition="add",
         repo="https://github.com/addyosmani/agent-skills", bookmark="2096252768633995734",
         risk="low", approval="no",
         summary="Production engineering skills. Install one workflow, not the whole tree."),
    dict(id="emil-skills", name="Emil Kowalski skills", category="skills", kind="skill", disposition="add",
         repo="https://github.com/emilkowalski/skills", bookmark="2075536512024994039",
         risk="low", approval="no",
         summary="Design-agent skills from Emil Kowalski."),
    dict(id="impeccable", name="Impeccable", category="skills", kind="skill", disposition="add",
         repo="https://impeccable.style/", bookmark="2075536512024994039",
         risk="low", approval="no",
         summary="Design skill named beside Emil Kowalski's list. Site, not a GitHub repo, in the resolved link."),
    dict(id="taste-skill", name="taste-skill", category="skills", kind="skill", disposition="add",
         repo="https://github.com/Leonxlnx/taste-skill", bookmark="2033322376440549682",
         risk="low", approval="no",
         summary="A taste skill for design judgment."),
    dict(id="taste", name="Taste", category="skills", kind="skill", disposition="add",
         repo="https://www.tasteskill.dev/", bookmark="2075536512024994039",
         risk="low", approval="no",
         summary="Design taste skill from the same design list. Different source from taste-skill."),
    dict(id="layers", name="Layers", category="skills", kind="skill", disposition="add",
         repo="https://layers.jamiemill.com/", bookmark="2075536512024994039",
         risk="low", approval="no",
         summary="Design skill named in the design-agent list."),
    dict(id="marketing-skills", name="Marketing Skills", category="skills", kind="skill", disposition="add",
         repo="https://github.com/coreyhaines31/marketingskills", bookmark="2035841006273548481",
         risk="medium", approval="yes",
         summary="Product-marketing skills: SEO, email, social, pricing, churn. Sending and ads wait for approval."),
    dict(id="pm-skills", name="PM Skills Marketplace", category="skills", kind="skill", disposition="add",
         repo="", bookmark="2029697412701282511",
         risk="low", approval="no",
         summary="Pawel Huryn's PM skills. The cache text names the marketplace and does not include a repository URL."),
    dict(id="kepano-obsidian", name="Obsidian skills", category="skills", kind="skill", disposition="add",
         repo="https://github.com/kepano/obsidian-skills", bookmark="2026801420872093708",
         risk="low", approval="no",
         summary="Kepano's skills for Obsidian markdown, Bases, Canvas, and the CLI."),
    dict(id="ffmpeg-skill", name="FFmpeg skill", category="skills", kind="skill", disposition="add",
         repo="https://github.com/kajisho5/ffmpeg-skill", bookmark="2096964158994755604",
         risk="low", approval="no",
         summary="Local video edits: crop, captions, Ken Burns, silence cut. Does not publish."),
    dict(id="executive-assistant", name="Executive assistant skills", category="skills", kind="skill", disposition="add",
         repo="https://github.com/mgonto/executive-assistant-skills", bookmark="2029013122506223688",
         risk="medium", approval="yes",
         summary="Inbox, calendar, and follow-up jobs. Port the jobs. Do not take the OpenClaw runtime. Sending waits for approval."),
    dict(id="fabric", name="Fabric", category="skills", kind="skill", disposition="add",
         repo="https://github.com/danielmiessler/Fabric", bookmark="2100625120691720385",
         risk="low", approval="no",
         summary="Reusable prompt patterns."),
    dict(id="docling", name="Docling", category="skills", kind="skill", disposition="add",
         repo="https://github.com/docling-project/docling", bookmark="2100625120691720385",
         risk="low", approval="no",
         summary="Document parsing when Hermes' built-in reader is not enough."),
    dict(id="pageindex", name="PageIndex", category="skills", kind="skill", disposition="add",
         repo="https://github.com/VectifyAI/PageIndex", bookmark="2100625120691720385",
         risk="low", approval="no",
         summary="Page-level index over long documents."),
    dict(id="markitdown", name="MarkItDown", category="skills", kind="skill", disposition="add",
         repo="https://github.com/microsoft/markitdown", bookmark="2090476415661830285",
         risk="low", approval="no",
         summary="Office, PDF, and audio files into markdown for the company repo."),
    dict(id="html-video", name="html-video", category="skills", kind="skill", disposition="add",
         repo="https://github.com/nexu-io/html-video", bookmark="2062470358687498470",
         risk="low", approval="no",
         summary="Local HTML-to-MP4. Hermes is one of the agents it detects."),
    dict(id="hyperframes", name="Hyperframes", category="skills", kind="skill", disposition="add",
         repo="https://github.com/heygen-com/hyperframes", bookmark="2100625120691720385",
         risk="low", approval="no",
         summary="Video frames in the agent stack post."),
    dict(id="openmontage", name="OpenMontage", category="skills", kind="skill", disposition="add",
         repo="https://github.com/calesthio/OpenMontage", bookmark="2100625120691720385",
         risk="low", approval="no",
         summary="Montage and edit step in the agent stack post."),
    dict(id="trendradar", name="TrendRadar", category="skills", kind="skill", disposition="add",
         repo="https://github.com/sansan0/TrendRadar", bookmark="2100625120691720385",
         risk="low", approval="no",
         summary="Watch what changed. A healthy day still sends nothing."),
    dict(id="career-ops", name="career-ops", category="skills", kind="skill", disposition="add",
         repo="https://github.com/career-ops-hq/career-ops", bookmark="2101399836587331901",
         risk="medium", approval="yes",
         summary="Career operations skill. Outreach waits for approval."),
    dict(id="resume-skills", name="ResumeSkills", category="skills", kind="skill", disposition="add",
         repo="https://github.com/Paramchoudhary/ResumeSkills", bookmark="2101399836587331901",
         risk="low", approval="no",
         summary="Resume skill from the 20-skill stack."),
    dict(id="notebooklm-skill", name="notebooklm-skill", category="skills", kind="skill", disposition="add",
         repo="https://github.com/PleasePrompto/notebooklm-skill", bookmark="2101399836587331901",
         risk="low", approval="no",
         summary="NotebookLM skill from the 20-skill stack."),
    dict(id="tutor-skills", name="tutor-skills", category="skills", kind="skill", disposition="add",
         repo="https://github.com/bevibing/tutor-skills", bookmark="2101399836587331901",
         risk="low", approval="no",
         summary="Tutor skills from the 20-skill stack."),
    dict(id="youtube-skills", name="youtube-skills", category="skills", kind="skill", disposition="add",
         repo="https://github.com/ZeroPointRepo/youtube-skills", bookmark="2101399836587331901",
         risk="low", approval="no",
         summary="YouTube skills from the 20-skill stack. Publishing waits for approval."),
    dict(id="translate-book", name="translate-book", category="skills", kind="skill", disposition="add",
         repo="https://github.com/deusyu/translate-book", bookmark="2101399836587331901",
         risk="low", approval="no",
         summary="Book translation skill from the 20-skill stack."),
    dict(id="creative-director", name="creative-director", category="skills", kind="skill", disposition="add",
         repo="https://github.com/smixs/creative-director-skill", bookmark="2101399836587331901",
         risk="low", approval="no",
         summary="Creative direction skill from the 20-skill stack."),
    dict(id="color-expert", name="color-expert", category="skills", kind="skill", disposition="add",
         repo="https://github.com/meodai/skill.color-expert", bookmark="2101399836587331901",
         risk="low", approval="no",
         summary="Color skill from the 20-skill stack."),
    dict(id="platform-design", name="platform-design", category="skills", kind="skill", disposition="add",
         repo="https://github.com/ehmo/platform-design-skills", bookmark="2101399836587331901",
         risk="low", approval="no",
         summary="Platform design skills from the 20-skill stack."),
    dict(id="product-manager-skills", name="product-manager-skills", category="skills", kind="skill", disposition="add",
         repo="https://github.com/Digidai/product-manager-skills", bookmark="2101399836587331901",
         risk="low", approval="no",
         summary="Product manager skills from the 20-skill stack."),
    dict(id="aegis", name="Aegis", category="skills", kind="skill", disposition="add",
         repo="https://github.com/GanyuanRan/Aegis", bookmark="2101399836587331901",
         risk="medium", approval="no",
         summary="Named in the 20-skill stack. Read the repo before trusting it."),
    dict(id="terraform-skill", name="terraform-skill", category="skills", kind="skill", disposition="add",
         repo="https://github.com/antonbabenko/terraform-skill", bookmark="2101399836587331901",
         risk="high", approval="yes",
         summary="Infrastructure changes. Apply waits for approval."),
    dict(id="qdrant-skills", name="qdrant-skills", category="skills", kind="skill", disposition="add",
         repo="https://github.com/qdrant/skills", bookmark="2101399836587331901",
         risk="low", approval="no",
         summary="Qdrant skills. The company repo stays the source of record."),
    dict(id="vibe-skills", name="Vibe-Skills", category="skills", kind="skill", disposition="add",
         repo="https://github.com/foryourhealth111-pixel/Vibe-Skills", bookmark="2101399836587331901",
         risk="low", approval="no",
         summary="Named in the 20-skill stack. Read the repo before installing it."),
    dict(id="skill-seekers", name="Skill Seekers", category="skills", kind="skill", disposition="add",
         repo="https://github.com/yusufkaraaslan/Skill_Seekers", bookmark="2101399836587331901",
         risk="low", approval="no",
         summary="Builds a skill from documentation. Review the generated skill before enabling it."),
    dict(id="postiz-agent", name="postiz-agent", category="skills", kind="skill", disposition="add",
         repo="https://github.com/gitroomhq/postiz-agent", bookmark="2101399836587331901",
         risk="high", approval="yes",
         summary="Social publishing. A post waits for approval."),
    dict(id="email-marketing-bible", name="email-marketing-bible", category="skills", kind="skill", disposition="add",
         repo="https://github.com/CosmoBlk/email-marketing-bible", bookmark="2101399836587331901",
         risk="high", approval="yes",
         summary="Email marketing. Sending waits for approval."),
    dict(id="gtm-cofounder", name="gtm-cofounder", category="skills", kind="skill", disposition="add",
         repo="https://github.com/AIDevGTM/gtm-cofounder", bookmark="2101399836587331901",
         risk="high", approval="yes",
         summary="Go-to-market skill. Outreach waits for approval."),
    dict(id="charlie-cfo", name="charlie-cfo", category="skills", kind="skill", disposition="add",
         repo="https://github.com/EveryInc/charlie-cfo-skill", bookmark="2101399836587331901",
         risk="high", approval="yes",
         summary="Finance skill. Money movement waits for approval."),
    dict(id="founder-skills", name="founder-skills", category="skills", kind="skill", disposition="add",
         repo="https://github.com/ognjengt/founder-skills", bookmark="2101399836587331901",
         risk="low", approval="no",
         summary="Founder skills from the 20-skill stack."),
    dict(id="jev", name="TypeSafe Jev", category="skills", kind="skill", disposition="add",
         repo="https://github.com/typesafe-ai/skills", bookmark="2100917158922387537",
         risk="low", approval="no",
         summary="Yes/no and score calls. Not a third model seat. Install with npx skills add typesafe-ai/skills --skill typesafe-ai."),
    dict(id="ai-engineering-hub", name="AI Engineering Hub", category="other", kind="catalog", disposition="add",
         repo="https://github.com/patchy631/ai-engineering-hub", bookmark="2100625120691720385",
         risk="low", approval="no",
         summary="Example repo from the 15-project stack. Read it. Do not treat it as a runtime."),
    # --- plugins ---
    dict(id="refactoring-ui", name="Refactoring UI plugin", category="plugins", kind="plugin", disposition="add",
         repo="https://github.com/gnurio/refactoring-ui-plugin", bookmark="2075536512024994039",
         risk="low", approval="no",
         summary="Polish pass based on Refactoring UI, from the design-agent list."),
    dict(id="pixelrag", name="PixelRAG", category="plugins", kind="plugin", disposition="add",
         repo="", bookmark="2068639188396744937",
         risk="medium", approval="no",
         summary="Reads a page from a screenshot. The cache text does not include a repository URL. Hermes vision plus browser covers the same job when this is off."),
    # --- other capabilities ---
    dict(id="awesome-mcp", name="awesome-mcp-servers", category="other", kind="catalog", disposition="add",
         repo="https://github.com/punkpeye/awesome-mcp-servers", bookmark="2096252768633995734",
         risk="low", approval="no",
         summary="A directory of MCP servers. Pick one server. Do not enable the directory."),
    dict(id="xmcp", name="X MCP", category="other", kind="mcp", disposition="add",
         repo="https://github.com/xdevplatform/xmcp", bookmark="2040937372909531286",
         risk="high", approval="yes",
         summary="X platform MCP. Reading can use Hermes x_search. Posting waits for approval."),
    dict(id="revenuecat", name="RevenueCat MCP", category="other", kind="mcp", disposition="add",
         repo="", bookmark="1981787308887253146",
         risk="high", approval="yes",
         summary="Subscriptions and entitlements. Billing writes wait for approval. No repository URL in the cache text."),
    dict(id="lazyweb", name="Lazyweb", category="other", kind="mcp", disposition="add",
         repo="", bookmark="2050579689249333722",
         risk="low", approval="no",
         summary="Design-research MCP and six skills. No repository URL in the cache text."),
    dict(id="component-library", name="Component library MCP", category="other", kind="mcp", disposition="add",
         repo="", bookmark="2082689872494755872",
         risk="low", approval="no",
         summary="Danny Postma's component MCP. The short link resolved back to the post, not a repository."),
    dict(id="mobile-mcp", name="Mobile MCP", category="other", kind="mcp", disposition="add",
         repo="", bookmark="2097159242411077994",
         risk="high", approval="yes",
         summary="Drives iOS and Android devices. No repository URL in the cache text. Approval before it taps a device."),
    dict(id="tinyfish", name="TinyFish", category="other", kind="mcp", disposition="add",
         repo="https://github.com/tinyfish-io/tinyfish-mcp-server", bookmark="2035178397648003507",
         risk="high", approval="yes",
         summary="Web automation MCP. The five-app post only names this one. Paid runs and logins wait for approval."),
    dict(id="firecrawl", name="Firecrawl", category="other", kind="cli", disposition="add",
         repo="https://github.com/firecrawl/firecrawl", bookmark="2071040656634732984",
         risk="medium", approval="no",
         summary="Crawl when Hermes web extract is not enough. Broad crawls wait for approval."),
    dict(id="agent-reach", name="Agent-Reach", category="other", kind="cli", disposition="add",
         repo="https://github.com/Panniantong/Agent-Reach", bookmark="2101223518570488027",
         risk="medium", approval="yes",
         summary="Read-only reach across sites. Anything that posts waits for approval."),
    dict(id="calcom", name="Cal.com", category="other", kind="cli", disposition="add",
         repo="https://github.com/calcom/cal.com", bookmark="2097364320149725205",
         risk="medium", approval="yes",
         summary="Scheduling product. Creating or changing a booking waits for approval."),
    dict(id="open-seo", name="open-seo", category="other", kind="cli", disposition="add",
         repo="https://github.com/every-app/open-seo", bookmark="2093013941412852083",
         risk="low", approval="no",
         summary="SEO tooling from the every-app post."),
    dict(id="graft", name="Graft", category="other", kind="cli", disposition="add",
         repo="https://github.com/NanoNets/Graft", bookmark="2091157554919280688",
         risk="low", approval="no",
         summary="Context compression beside Hermes. Hermes compression stays the default."),
    # --- already in Hermes ---
    dict(id="hermes-kanban", name="Kanban", category="other", kind="builtin", disposition="builtin",
         repo="https://github.com/NousResearch/hermes-agent", bookmark="2100625120691720385",
         risk="low", approval="no",
         summary="The board. Do not install a second one."),
    dict(id="hermes-cron", name="Cron", category="other", kind="builtin", disposition="builtin",
         repo="https://github.com/NousResearch/hermes-agent", bookmark="2100625120691720385",
         risk="low", approval="no",
         summary="Gateway scheduler. Blueprints stay suggestions until accepted."),
    dict(id="hermes-memory", name="Memory", category="other", kind="builtin", disposition="builtin",
         repo="https://github.com/NousResearch/hermes-agent", bookmark="2100625120691720385",
         risk="low", approval="no",
         summary="MEMORY.md and USER.md. The company repo holds company facts."),
    dict(id="hermes-web", name="Web search and extract", category="other", kind="builtin", disposition="builtin",
         repo="https://github.com/NousResearch/hermes-agent", bookmark="2027439397449437288",
         risk="low", approval="no",
         summary="Built-in fetch. Scrapling is not the fetch path."),
    dict(id="hermes-browser", name="Browser", category="other", kind="builtin", disposition="builtin",
         repo="https://github.com/NousResearch/hermes-agent", bookmark="2043706042828394747",
         risk="medium", approval="yes",
         summary="Built-in browser. Logged-in founder browsers stay off."),
    dict(id="hermes-docs", name="Document extraction", category="other", kind="builtin", disposition="builtin",
         repo="https://github.com/NousResearch/hermes-agent", bookmark="2090476415661830285",
         risk="low", approval="no",
         summary="Built-in reader. Docling and MarkItDown are the overflow."),
    dict(id="hermes-x-search", name="X search", category="other", kind="builtin", disposition="builtin",
         repo="https://github.com/NousResearch/hermes-agent", bookmark="2040937372909531286",
         risk="low", approval="no",
         summary="Built-in read of X. Posting is the X MCP, with approval."),
    dict(id="hermes-codex", name="Codex seat", category="skills", kind="builtin", disposition="builtin",
         repo="https://github.com/NousResearch/hermes-agent", bookmark="2038677236304245087",
         risk="low", approval="no",
         summary="Bundled codex skill plus the coder profile. See docs/seats.md."),
    dict(id="hermes-claude-code", name="Claude Code skill", category="skills", kind="builtin", disposition="builtin",
         repo="https://github.com/NousResearch/hermes-agent", bookmark="2030569383999701457",
         risk="low", approval="no",
         summary="Bundled claude-code skill. This profile stays the Claude seat."),
    dict(id="hermes-sessions", name="Session search", category="other", kind="builtin", disposition="builtin",
         repo="https://github.com/NousResearch/hermes-agent", bookmark="2029919688713719809",
         risk="low", approval="no",
         summary="Hermes already searches sessions. QMD is not a second store."),
    dict(id="hermes-compression", name="Context compression", category="other", kind="builtin", disposition="builtin",
         repo="https://github.com/headroomlabs-ai/headroom", bookmark="2100625120691720385",
         risk="low", approval="no",
         summary="Hermes compression. headroom is the same job."),
    dict(id="hermes-google-workspace", name="Google Workspace", category="other", kind="builtin", disposition="builtin",
         repo="https://github.com/NousResearch/hermes-agent", bookmark="2029013122506223688",
         risk="medium", approval="yes",
         summary="Bundled Gmail, Calendar, and Drive skill. Sending waits for approval."),
    # --- not offered ---
    dict(id="clawhub", name="ClawHub", category="skills", kind="catalog", disposition="shelf",
         repo="", bookmark="2036898530040668372",
         risk="high", approval="yes",
         summary="Bulk skill hub. The same cache says about one in eight skills was hostile."),
    dict(id="awesome-openclaw-skills", name="Awesome OpenClaw Skills", category="skills", kind="catalog", disposition="shelf",
         repo="", bookmark="2029877033489289597",
         risk="high", approval="yes",
         summary="OpenClaw skill dump. Not offered."),
    dict(id="antigravity-awesome-skills", name="Antigravity Awesome Skills", category="skills", kind="catalog", disposition="shelf",
         repo="https://github.com/sickn33/antigravity-awesome-skills", bookmark="2027336259040133499",
         risk="high", approval="yes",
         summary="Hundreds of skills in one install. Not offered."),
    dict(id="agency-agents", name="agency-agents", category="skills", kind="catalog", disposition="shelf",
         repo="https://github.com/msitarzewski/agency-agents", bookmark="2091157554919280688",
         risk="low", approval="no",
         summary="A second org chart. Departments in the company repo already do that job."),
    dict(id="awesome-claude-code", name="Awesome Claude Code", category="other", kind="catalog", disposition="shelf",
         repo="https://github.com/hesreallyhim/awesome-claude-code", bookmark="2035915909966229733",
         risk="low", approval="no",
         summary="A directory of links, not a tool to enable."),
    dict(id="founders-kit", name="Founders Kit", category="other", kind="catalog", disposition="shelf",
         repo="", bookmark="2029874602621686154",
         risk="low", approval="no",
         summary="Essay pack, not a connector."),
    dict(id="goose", name="Goose", category="other", kind="runtime", disposition="shelf",
         repo="https://github.com/block/goose", bookmark="2090476415661830285",
         risk="low", approval="no",
         summary="Another agent runtime."),
    dict(id="librechat", name="LibreChat", category="other", kind="runtime", disposition="shelf",
         repo="https://github.com/danny-avila/LibreChat", bookmark="2098941338297458746",
         risk="low", approval="no",
         summary="Another chat shell."),
    dict(id="lobehub", name="LobeHub", category="other", kind="runtime", disposition="shelf",
         repo="", bookmark="2087293827002638525",
         risk="low", approval="no",
         summary="Another operator product."),
    dict(id="paperclip", name="Paperclip", category="other", kind="runtime", disposition="shelf",
         repo="", bookmark="2030604968416412144",
         risk="low", approval="no",
         summary="A retired company layer. Kanban is the board."),
    dict(id="lobster-board", name="Lobster Board", category="other", kind="runtime", disposition="shelf",
         repo="", bookmark="2029962626579710258",
         risk="low", approval="no",
         summary="An OpenClaw mission control. Kanban is the board."),
    dict(id="myclaw", name="MyClaw Backup", category="other", kind="cli", disposition="shelf",
         repo="", bookmark="2029168044862537778",
         risk="low", approval="no",
         summary="OpenClaw backup. Hermes checkpoints cover this profile."),
    dict(id="siftly", name="Siftly", category="other", kind="cli", disposition="shelf",
         repo="", bookmark="2030065384423051482",
         risk="low", approval="no",
         summary="A second bookmark store. Field Theory already holds the cache."),
    dict(id="trading-agents", name="TradingAgents", category="other", kind="runtime", disposition="shelf",
         repo="https://github.com/TauricResearch/TradingAgents", bookmark="2098941338297458746",
         risk="high", approval="yes",
         summary="Trading autopilot. Not offered."),
    dict(id="autohedge", name="AutoHedge", category="other", kind="runtime", disposition="shelf",
         repo="https://github.com/The-Swarm-Corporation/AutoHedge", bookmark="2096254869674058124",
         risk="high", approval="yes",
         summary="Trading autopilot. Not offered."),
    dict(id="vibe-trading", name="Vibe-Trading", category="other", kind="runtime", disposition="shelf",
         repo="https://github.com/HKUDS/Vibe-Trading", bookmark="2096254869674058124",
         risk="high", approval="yes",
         summary="Trading autopilot. Not offered."),
    dict(id="chromex", name="chromex", category="plugins", kind="plugin", disposition="shelf",
         repo="https://github.com/GENEXIS-AI/chromex", bookmark="2049484893877637359",
         risk="high", approval="yes",
         summary="Injects Codex into the founder's Chrome. Not offered."),
    dict(id="supermemory", name="supermemory", category="other", kind="cli", disposition="shelf",
         repo="", bookmark="2033176475898433946",
         risk="low", approval="no",
         summary="A second memory beside the company repo."),
    dict(id="mem0", name="mem0", category="other", kind="cli", disposition="shelf",
         repo="https://github.com/mem0ai/mem0", bookmark="2100625120691720385",
         risk="low", approval="no",
         summary="A second memory beside the company repo."),
    dict(id="daytona", name="Daytona", category="other", kind="cli", disposition="shelf",
         repo="https://github.com/daytonaio/daytona", bookmark="2100625120691720385",
         risk="low", approval="no",
         summary="A Hermes terminal backend, not a company connector."),
    dict(id="scrapling", name="Scrapling", category="other", kind="cli", disposition="shelf",
         repo="https://github.com/D4Vinci/Scrapling", bookmark="2027439397449437288",
         risk="high", approval="yes",
         summary="Advertised as a Cloudflare bypass. Fetch stays on the built-in web tool."),
    dict(id="clawwork", name="ClawWork", category="other", kind="runtime", disposition="shelf",
         repo="https://github.com/HKUDS/ClawWork", bookmark="2090476415661830285",
         risk="high", approval="yes",
         summary="Agent earn-money arena. Not offered."),
    dict(id="money-printer-plus", name="MoneyPrinterPlus", category="other", kind="cli", disposition="shelf",
         repo="https://github.com/ddean2009/MoneyPrinterPlus", bookmark="2090476415661830285",
         risk="high", approval="yes",
         summary="Auto-publishes short video. Not offered."),
    dict(id="aitoearn", name="AiToEarn", category="other", kind="runtime", disposition="shelf",
         repo="https://github.com/chenjinzhou/AiToEarn", bookmark="2090476415661830285",
         risk="high", approval="yes",
         summary="Auto-posts and auto-engages. Not offered."),
    dict(id="money-printer-turbo", name="MoneyPrinterTurbo", category="other", kind="cli", disposition="shelf",
         repo="https://github.com/harry0703/MoneyPrinterTurbo", bookmark="2090476415661830285",
         risk="high", approval="yes",
         summary="Auto short-video factory. Not offered."),
    dict(id="make-money-with-ai", name="MakeMoneyWithAI", category="other", kind="catalog", disposition="shelf",
         repo="https://github.com/garylab/MakeMoneyWithAI", bookmark="2090476415661830285",
         risk="low", approval="no",
         summary="A directory of money projects, not a tool."),
    dict(id="openclaw-money-maker", name="OpenClaw money-maker list", category="other", kind="catalog", disposition="shelf",
         repo="https://github.com/BlockRunAI/awesome-OpenClaw-Money-Maker", bookmark="2090476415661830285",
         risk="high", approval="yes",
         summary="OpenClaw money tools, including a wallet agent. Not offered."),
    dict(id="openclaw-codex-plugin", name="OpenClaw Codex plugin", category="plugins", kind="plugin", disposition="shelf",
         repo="https://github.com/pwrdrvr/openclaw-codex-app-server", bookmark="2037290981108658494",
         risk="high", approval="yes",
         summary="Codex through OpenClaw. The Codex seat is the coder profile."),
]
