#!/usr/bin/env python3
"""Write connectors/registry.yaml, registry.json, and catalog/cards/*/SKILL.md."""

from __future__ import annotations

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from catalog_data import ITEMS  # noqa: E402

ROOT = Path(__file__).resolve().parents[1]
REQUIRED = ("id", "name", "category", "kind", "disposition", "repo", "bookmark", "risk", "approval", "summary")
CATEGORIES = {"skills", "plugins", "other"}
DISPOSITIONS = {"add", "builtin", "shelf"}


def yaml_quote(value: str) -> str:
    if value == "":
        return '""'
    if any(ch in value for ch in ":#{}[]&*!|>%@`'\"\n"):
        escaped = value.replace("\\", "\\\\").replace('"', '\\"')
        return f'"{escaped}"'
    return value


def write_yaml(path: Path) -> None:
    lines = [
        "# Generated by scripts/sync_catalog.py from scripts/catalog_data.py.",
        "# Composio is intentionally absent. Nothing here is enabled.",
        "items:",
    ]
    for item in ITEMS:
        lines.append(f"  - id: {yaml_quote(item['id'])}")
        for key in REQUIRED[1:]:
            lines.append(f"    {key}: {yaml_quote(item[key])}")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def skill_body(item: dict[str, str]) -> str:
    repo = item["repo"] or "The bookmark cache does not include a repository URL."
    install = (
        f"npx skills add {item['repo']}"
        if item["repo"].startswith("https://github.com/")
        else "No install command. The source is the site or the bookmark."
    )
    description = (item["name"] + ". " + item["summary"]).replace('"', "'")
    return f"""---
name: {item['id']}
description: "{description}"
version: 0.1.0
author: Thoughtseed
license: MIT
metadata:
  hermes:
    tags: [catalog, {item['category']}, factor]
    related_skills: [connector-gate, company-context]
---

# {item['name']}

Factor card for an upstream {item['kind']}. This file is not a copy of that project.

## When to use

{item['summary']}

Load this only when `connectors/enabled.yaml` lists `{item['id']}`.

## Source

- Bookmark `{item['bookmark']}`
- {repo}
- Risk `{item['risk']}`. Approval `{item['approval']}`.
- Public sends, spend, and paid calls wait for an approval comment even when approval is no.

## Procedure

1. Load `connector-gate` and confirm `{item['id']}` is enabled.
2. If the upstream is not installed, give the founder this command and stop:

   `{install}`

3. Read the upstream before running it. Follow its own instructions for the task.
4. Write results into the company repo path named on the card. Do not invent company facts.
"""


def write_skills(catalog: Path) -> None:
    if catalog.exists():
        for child in catalog.iterdir():
            if child.is_dir():
                for file in child.glob("SKILL.md"):
                    file.unlink()
                child.rmdir()
    catalog.mkdir(parents=True, exist_ok=True)
    for item in ITEMS:
        if item["disposition"] != "add":
            continue
        folder = catalog / item["id"]
        folder.mkdir()
        (folder / "SKILL.md").write_text(skill_body(item), encoding="utf-8")


def validate() -> None:
    seen: set[str] = set()
    for item in ITEMS:
        for key in REQUIRED:
            if key not in item:
                raise SystemExit(f"{item.get('id', '?')} missing {key}")
        if item["id"] in seen:
            raise SystemExit(f"duplicate id {item['id']}")
        seen.add(item["id"])
        if item["category"] not in CATEGORIES:
            raise SystemExit(f"{item['id']} bad category")
        if item["disposition"] not in DISPOSITIONS:
            raise SystemExit(f"{item['id']} bad disposition")
        if not item["id"].replace("-", "").isalnum() or "--" in item["id"]:
            raise SystemExit(f"bad id {item['id']}")


def main() -> int:
    validate()
    write_yaml(ROOT / "connectors" / "registry.yaml")
    (ROOT / "connectors" / "registry.json").write_text(
        json.dumps(ITEMS, indent=2) + "\n", encoding="utf-8"
    )
    stale = ROOT / "skills" / "catalog"
    if stale.exists():
        for child in stale.iterdir():
            if child.is_dir():
                for file in child.glob("SKILL.md"):
                    file.unlink()
                child.rmdir()
        stale.rmdir()
    write_skills(ROOT / "catalog" / "cards")
    offered = sum(1 for item in ITEMS if item["disposition"] == "add")
    print(f"wrote {len(ITEMS)} registry rows, {offered} catalog skills")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
